USE FLYEASY;

CREATE TABLE IF NOT EXISTS User (
  ID               INTEGER PRIMARY KEY AUTO_INCREMENT,
  Name             VARCHAR(255) NOT NULL,
  LastName         VARCHAR(255) DEFAULT NULL,
  SurName          VARCHAR(255) DEFAULT NULL,
  Email            VARCHAR(255) UNIQUE NOT NULL,
  PhoneNumber      VARCHAR(30) UNIQUE DEFAULT NULL,
  PasswordHash     VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Location (
  ID               INTEGER PRIMARY KEY AUTO_INCREMENT,
  LocName          VARCHAR(255) NOT NULL,
  Popularity       FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS Ticket (
  ID              INTEGER PRIMARY KEY AUTO_INCREMENT,
  DeparteLocID    INTEGER NOT NULL,
  ArriveLocID     INTEGER NOT NULL,
  Price           INTEGER DEFAULT NULL,
  IsBusiness      BOOLEAN DEFAULT FALSE,
  Airline         VARCHAR(255) NOT NULL,
  DepTime         TIME NOT NULL,
  DepDate         DATE NOT NULL,
  ChCode          VARCHAR(255) NOT NULL,
  TimeTaken       VARCHAR(100) NOT NULL,

  FOREIGN KEY (DeparteLocID) REFERENCES Location(ID)
  ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (ArriveLocID) REFERENCES Location(ID)
  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Tokens (
  Token           VARCHAR(100) UNIQUE NOT NULL,
  UserID          INTEGER UNIQUE NOT NULL,

  FOREIGN KEY (UserID) REFERENCES User(ID)
  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS UserTickets (
  UserID           INTEGER NOT NULL,
  TicketID         INTEGER NOT NULL,

  FOREIGN KEY (UserID) REFERENCES User(ID),
  FOREIGN KEY (TicketID) REFERENCES Ticket(ID)
  ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Favorites (
  UserID          INTEGER NOT NULL,
  LocationID      INTEGER NOT NULL,

  FOREIGN KEY (UserID) REFERENCES User(ID)
  ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (LocationID) REFERENCES Location(ID)
  ON DELETE NO ACTION ON UPDATE CASCADE
);
